language: node_js
node_js:
  - 10.6.0
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
after_success:
#  - npm i -g firebase-ci
#  - firebase-ci deploy
  - firebase deploy
branches:
  only:
    - master
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
